name: flutterfly
description: A flutter template.

publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window: ^0.1.5
  conditioned: ^0.1.0-dev.1
  cupertino_icons: ^1.0.5
  dio: ^5.0.0
  fluent_ui: ^4.3.0
  flutter_hooks: ^0.18.5+1
  flutter_native_splash: ^2.2.17
  flutter_riverpod: ^2.2.0
  fpdart: ^0.4.0
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  nester: ^1.2.1
  niku: ^2.3.3
  riverpod_context: ^0.3.0
  shared_preferences: ^2.0.17
  tailwind_colors : ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  freezed: ^2.3.2
  icons_launcher: ^2.1.0
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: AminaReska
      fonts:
        - asset: assets/fonts/amina-reska.ttf
    - family: FuturaPTMedium
      fonts:
      - asset: assets/fonts/FuturaPTMedium.otf