name: "Github Deploy"
env:
  my_secret: ${{secrets.commit_secret}}
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: "Enabling Flutter for Web"
        run: flutter config --enable-web
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Enable for Publishing"
        run: sed -i 's/$FLUTTER_BASE_HREF/https:\/\/victor7w7r.github.io\/flutterfly\//' web/index.html
      - name: "Compiling.."
        run: flutter build web --web-renderer canvaskit
      - name: "Deploying.."
        run: |
          cd build/web
          git init
          git config --global user.email testvictor7w7r@gmail.com
          git config --global user.name victor7w7r
          git status
          git remote add origin https://${{secrets.commit_secret}}@github.com/victor7w7r/flutterfly.git
          git checkout -b pages
          git add --all
          git commit -m "update"
          git push origin pages -f
